package presentacion.comandos;

public enum IDEventos {
	
	/* CLIENTES */
	EVENTO_ALTA_CLIENTE, ERROR_ALTA_CLIENTE,
	EVENTO_BAJA_CLIENTE, ERROR_BAJA_CLIENTE,
	EVENTO_MODIFICAR_CLIENTE, ERROR_MODIFICAR_CLIENTE,
	EVENTO_CONSULTAR_CLIENTE, ERROR_CONSULTAR_CLIENTE,
	EVENTO_CONSULTAR_TODOS_CLIENTE, ERROR_CONSULTAR_TODOS_CLIENTE,
	EVENTO_CONSULTAR_CLIENTE_V_BORRAR, ERROR_CONSULTAR_CLIENTE_V_BORRAR,
	EVENTO_CONSULTAR_CLIENTE_V_MODIFICAR, ERROR_CONSULTAR_CLIENTE_V_MODIFICAR,
	
	/* RESERVAS */
	EVENTO_ALTA_RESERVA, ERROR_ALTA_RESERVA,
	EVENTO_BAJA_RESERVA, ERROR_BAJA_RESERVA,
	EVENTO_MODIFICAR_RESERVA, ERROR_MODIFICAR_RESERVA,
	EVENTO_CONSULTAR_RESERVA, ERROR_CONSULTAR_RESERVA,
	EVENTO_CONSULTAR_TODAS_RESERVAS, ERROR_CONSULTAR_TODAS_RESERVAS,
	EVENTO_CONSULTAR_CLIENTE_V_ALTA_RESERVAS, ERROR_CONSULTAR_CLIENTE_V_ALTA_RESERVAS,
	EVENTO_CONSULTAR_RESERVA_V_MODIFICAR_RESERVAS, ERROR_CONSULTAR_RESERVA_V_MODIFICAR_RESERVAS,
	EVENTO_CONSULTAR_TODAS_RESERVAS_POR_CLIENTE, ERROR_CONSULTAR_TODAS_RESERVAS_POR_CLIENTE,
	EVENTO_CONSULTAR_RESERVA_V_BORRAR_RESERVAS, ERROR_CONSULTAR_RESERVA_V_BORRAR_RESERVAS,
	EVENTO_CONSULTAR_CLIENTE_V_BORRAR_RESERVAS, ERROR_CONSULTAR_CLIENTE_V_BORRAR_RESERVAS,
	
	/* HABITACIONES */
	EVENTO_ALTA_HABITACION, ERROR_ALTA_HABITACION,
	EVENTO_BAJA_HABITACION, ERROR_BAJA_HABITACION,
	EVENTO_MODIFICAR_HABITACION, ERROR_MODIFICAR_HABITACION,
	EVENTO_CONSULTAR_HABITACION, ERROR_CONSULTAR_HABITACION,
	EVENTO_CONSULTAR_TODAS_HABITACION, ERROR_CONSULTAR_TODAS_HABITACION,
	EVENTO_CONSULTAR_HABITACION_V_ALTA, ERROR_CONSULTAR_HABITACION_V_ALTA,
	EVENTO_CONSULTAR_HABITACION_V_BAJA, ERROR_CONSULTAR_HABITACION_V_BAJA,
	EVENTO_CONSULTAR_HABITACION_V_MODIFICAR, ERROR_CONSULTAR_HABITACION_V_MODIFICAR,
	
	/* DEPARTAMENTOS */
	EVENTO_ALTA_DEPARTAMENTO, ERROR_ALTA_DEPARTAMENTO,
	EVENTO_BAJA_DEPARTAMENTO, ERROR_BAJA_DEPARTAMENTO,
	EVENTO_MODIFICAR_DEPARTAMENTO, ERROR_MODIFICAR_DEPARTAMENTO,
	EVENTO_CONSULTAR_DEPARTAMENTO, ERROR_CONSULTAR_DEPARTAMENTO,
	EVENTO_CONSULTAR_TODOS_DEPARTAMENTO, ERROR_CONSULTAR_TODOS_DEPARTAMENTO,
	EVENTO_CONSULTAR_DEPARTAMENTO_V_BORRAR, ERROR_CONSULTAR_DEPARTAMENTO_V_BORRAR,
	EVENTO_CONSULTAR_DEPARTAMENTO_V_MODIFICAR, ERROR_CONSULTAR_DEPARTAMENTO_V_MODIFICAR,
	
	/* EMPLEADOS */
	EVENTO_ALTA_EMPLEADO, ERROR_ALTA_EMPLEADO,
	EVENTO_BAJA_EMPLEADO, ERROR_BAJA_EMPLEADO,
	EVENTO_MODIFICAR_EMPLEADO, ERROR_MODIFICAR_EMPLEADO,
	EVENTO_CONSULTAR_EMPLEADO, ERROR_CONSULTAR_EMPLEADO,
	EVENTO_ASIGNARTAREA_EMPLEADO, ERROR_ASIGNARTAREA_EMPLEADO,
	EVENTO_CONSULTAR_TODOS_EMPLEADOS, ERROR_CONSULTAR_TODOS_EMPLEADOS,
	EVENTO_CONSULTAR_TAREAS_V_ASIGARTAREA, ERROR_CONSULTAR_TAREAS_V_ASIGARTAREA,
	EVENTO_CONSULTAR_EMPLEADO_V_ASIGARTAREA, ERROR_CONSULTAR_EMPLEADO_V_ASIGARTAREA,
	EVENTO_CONSULTAR_EMPLEADOS_V_BORRAR, ERROR_CONSULTAR_EMPLEADOS_V_BORRAR,
	EVENTO_CONSULTAR_EMPLEADOS_V_MODIFICAR, ERROR_CONSULTAR_EMPLEADOS_V_MODIFICAR,
	EVENTO_CONSULTAR_TODOS_DEPARTAMENTOS_V_ALTA_EMPLEADO, ERROR_CONSULTAR_TODOS_DEPARTAMENTOS_V_ALTA_EMPLEADO,
	
	/* TAREAS */
	EVENTO_ALTA_TAREA, ERROR_ALTA_TAREA,
	EVENTO_BAJA_TAREA, ERROR_BAJA_TAREA,
	EVENTO_MODIFICAR_TAREA, ERROR_MODIFICAR_TAREA,
	EVENTO_CONSULTAR_TAREA, ERROR_CONSULTAR_TAREA,
	EVENTO_CONSULTAR_TODAS_TAREAS, ERROR_CONSULTAR_TODAS_TAREAS,
	EVENTO_CONSULTAR_TAREAS_V_BORRAR, ERROR_CONSULTAR_TAREAS_V_BORRAR,
	EVENTO_CONSULTAR_TAREAS_V_MODIFICAR, ERROR_CONSULTAR_TAREAS_V_MODIFICAR,
}
