package presentacion.comandos;

public enum IDEventos {

	EVENTO_ALTA_CLIENTE, ERROR_ALTA_CLIENTE, EVENTO_BAJA_CLIENTE, ERROR_BAJA_CLIENTE, EVENTO_ACTUALIZAR_CLIENTE, ERROR_ACTUALIZAR_CLIENTE, EVENTO_OBTENER_CLIENTE, ERROR_OBTENER_CLIENTE, EVENTO_OBTENER_TODOS_CLIENTE, ERROR_OBTENER_TODOS_CLIENTE,
	EVENTO_ALTA_RESERVA, ERROR_ALTA_RESERVA, EVENTO_BAJA_RESERVA, ERROR_BAJA_RESERVA, EVENTO_MODIFICAR_RESERVA,	 ERROR_MODIFICAR_RESERVA,  EVENTO_CONSULTAR_RESERVA, ERROR_CONSULTAR_RESERVA,EVENTO_CONSULTAR_TODAS_RESERVAS,ERROR_CONSULTAR_TODAS_RESERVAS;

}
